# Generated by Django 5.1.1 on 2024-09-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'блог-пост', 'verbose_name_plural': 'блог-посты'},
        ),
    ]
