# Generated by Django 5.1.1 on 2024-10-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('add_post', 'Can add post'), ('change_post', 'Can change post'), ('delete_post', 'Can delete post')], 'verbose_name': 'блог-пост', 'verbose_name_plural': 'блог-посты'},
        ),
    ]
